[book]
authors = ["hellowac"]
language = "en"
multilingual = false
src = "src"
title = "与资本,基本,股票,商业有关的知识汇总"

[build]
build-dir = "docs"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 1